### ISSUE TITLE
Error when opening files via the Mantra custom panes while the project tree view is collapsed.

### ISSUE THREAD

**Issue by Rongky** [mantrajs/mantrajs-atom-package#21]
Uncaught TypeError: Cannot read property 'expand' of undefined
/home/rongky/.atom/packages/mantrajs/lib/directoryHandler.coffee:82

-- Hide Stack Trace

TypeError: Cannot read property 'expand' of undefined at Function.module.exports.DirectoryHandler.revealActiveFile (/home/rongky/.atom/packages/mantrajs/lib/directoryHandler.coffee:82:15)
    at HTMLLIElement.<anonymous> (/home/rongky/.atom/packages/mantrajs/lib/directoryHandler.coffee:50:24)
    at HTMLOListElement.jQuery.event.dispatch (/home/rongky/.atom/packages/mantrajs/node_modules/space-pen/vendor/jquery.js:4681:9)
    at HTMLOListElement.elemData.handle (/home/rongky/.atom/packages/mantrajs/node_modules/space-pen/vendor/jquery.js:4359:28)

**Comment by tomitrescak** [comment]
Yes, the package is built on top of tree-view and cannot work without it. Sorry :/ I close this issue if you don't mind as there is no plan currently tu build a standalone package.
