### ISSUE TITLE
Uncaught TypeError: Cannot read property 'expand' of undefined

### ISSUE THREAD

**Issue by nadeemja** [mantrajs/mantrajs-atom-package#27]
[Enter steps to reproduce below:]
1. Enable: CTRL-ALT-O
2. Click a collection file in Configs -> lib -> collections

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [mantrajs](https://github.com/tomitrescak/mantrajs-atom-package) package, v0.4.4
### Stack Trace

Uncaught TypeError: Cannot read property 'expand' of undefined

```
At /Users/Nadeem/.atom/packages/mantrajs/lib/directoryHandler.coffee:87

TypeError: Cannot read property 'expand' of undefined
    at Function.module.exports.DirectoryHandler.revealActiveFile (/Users/Nadeem/.atom/packages/mantrajs/lib/directoryHandler.coffee:87:15)
    at HTMLLIElement.<anonymous> (/Users/Nadeem/.atom/packages/mantrajs/lib/mantra-pane-view.coffee:65:24)
    at HTMLLIElement.jQuery.event.dispatch (/Users/Nadeem/.atom/packages/mantrajs/node_modules/space-pen/vendor/jquery.js:4681:9)
    at HTMLLIElement.elemData.handle (/Users/Nadeem/.atom/packages/mantrajs/node_modules/space-pen/vendor/jquery.js:4359:28)
```
### Commands

```
     -1:06.2.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -0:59.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:56.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:56.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  3x -0:50.2.0 mantrajs:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "spell-check"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-lupa",
      "tool-bar",
      "sync-settings",
      "atom-ternjs"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Quick-JavaScript, v0.16.0
atom-bracket-highlight, v0.3.1
atom-ternjs, v0.14.1
autocomplete-modules, v1.4.1
docblockr, v0.7.3
emmet, v2.4.3
emmet-snippets-compatibility, v1.0.6
formatter, v2.12.3
formatter-jsbeautify, v1.0.2
highlight-column, v0.5.1
highlight-line, v0.11.1
language-babel, v2.24.1
lebab-convert, v0.9.0
linter, v1.11.4
linter-codeclimate, v0.1.2
linter-eslint, v7.2.2
linter-jscs, v4.0.2
mantrajs, v0.4.4
meteor-api, v2.20.0
opened-files, v0.3.6
react, v0.15.0
sync-settings, v0.7.2
tool-bar, v0.4.0
tool-bar-almighty, v0.6.1
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by macrozone** [comment]
It seems this happens if you toggle the project directory:

No exception if you click on a file:

<img width="351" alt="bildschirmfoto 2016-06-08 um 14 29 39" src="https://cloud.githubusercontent.com/assets/1972353/15894324/8f9aa43c-2d85-11e6-8a4f-477739d57aa0.png">

Throws exception when you click on a file:

<img width="377" alt="bildschirmfoto 2016-06-08 um 14 29 50" src="https://cloud.githubusercontent.com/assets/1972353/15894332/a3401d28-2d85-11e6-860e-02a20196ab61.png">

**Comment by Mokto** [comment]
Having this issue as well. But when I select a file in a module. 

It prevents me from using this great plugin :(
